#!/bin/bash

echo "🔍 Debug VPS2 Dashboard - Find the problem"
echo "=========================================="
echo ""
echo "Run these commands on VPS2:"
echo ""
echo "# 1. Check PM2 process info"
echo "pm2 info nexuslink-dashboard"
echo ""
echo "# Look for: 'cwd' path - this is the directory PM2 is serving"
echo ""
echo "# 2. Check git status in that directory"
echo "cd /www/wwwroot/nexuslink-project/nexuslink-dashboard"
echo "git log --oneline -3"
echo "# Should show: e402a2a feat: Update Dashboard with correct Agent installer"
echo ""
echo "# 3. Check actual file content"
echo "grep -n 'curl -fsSL' app/nodes/page.tsx"
echo "# Should find line with: curl -fsSL .../install.sh"
echo ""
echo "# 4. Check .next build timestamp"
echo "ls -lah .next/BUILD_ID"
echo "stat .next/BUILD_ID"
echo "# Should be recent (after your rebuild)"
echo ""
echo "# 5. Check PM2 logs for errors"
echo "pm2 logs nexuslink-dashboard --lines 100 --nostream"
echo ""
echo "# 6. Force PM2 to reload from disk"
echo "pm2 delete nexuslink-dashboard"
echo "pm2 start npm --name nexuslink-dashboard -- start"
echo ""
echo "=========================================="
echo ""
echo "ATAU coba cek PM2 ecosystem/config:"
echo "pm2 list"
echo "pm2 show nexuslink-dashboard"
