#!/bin/bash

# Force rebuild Dashboard di VPS2 (hapus cache)
# Location: /www/wwwroot/nexuslink-project/nexuslink-dashboard

echo "🔄 Force rebuild NexusLink Dashboard..."
echo "⚠️  Run this on VPS2 via SSH or aaPanel Terminal"
echo ""
echo "Commands:"
echo "=========================================="
echo ""
echo "cd /www/wwwroot/nexuslink-project/nexuslink-dashboard"
echo ""
echo "# Stop PM2 process first"
echo "pm2 stop nexuslink-dashboard"
echo ""
echo "# Pull latest changes"
echo "git pull origin main"
echo ""
echo "# Remove all cache and build artifacts"
echo "rm -rf .next"
echo "rm -rf node_modules/.cache"
echo ""
echo "# Optional: reinstall dependencies if package.json changed"
echo "# npm install"
echo ""
echo "# Build with fresh cache"
echo "npm run build"
echo ""
echo "# Restart PM2"
echo "pm2 restart nexuslink-dashboard"
echo ""
echo "# Check logs"
echo "pm2 logs nexuslink-dashboard --lines 50"
echo ""
echo "=========================================="
echo ""
echo "✅ After restart, hard refresh browser: Ctrl+Shift+R"
