#!/bin/bash
#
# NexusLink Production Deployment Script
# Automated installation of NexusLink API, Agent, or Dashboard
#
# Usage: sudo bash deploy.sh <component>
# Components: api, agent, dashboard, all
#

set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
INSTALL_DIR="/opt/nexuslink"
LOG_DIR="/var/log/nexuslink"
USER="nexus"
GROUP="nexus"
SOURCE_DIR=""

echo -e "${BLUE}"
cat << "EOF"
╔═══════════════════════════════════════╗
║   NexusLink Production Deployment    ║
║         Automated Installer          ║
╚═══════════════════════════════════════╝
EOF
echo -e "${NC}"

# Check if running as root
if [ "$EUID" -ne 0 ]; then 
    echo -e "${RED}❌ Please run as root (use sudo)${NC}"
    exit 1
fi

# Check arguments
if [ "$#" -ne 1 ]; then
    echo "Usage: $0 <component>"
    echo "Components: api, agent, dashboard, all"
    exit 1
fi

COMPONENT=$1

# Function to create user
create_user() {
    echo -e "\n${YELLOW}👤 Creating nexus user...${NC}"
    if id "$USER" &>/dev/null; then
        echo -e "${GREEN}✅ User $USER already exists${NC}"
    else
        useradd -r -s /bin/bash -d "$INSTALL_DIR" -m "$USER"
        echo -e "${GREEN}✅ User $USER created${NC}"
    fi
}

# Function to create directories
create_directories() {
    echo -e "\n${YELLOW}📁 Creating directories...${NC}"
    mkdir -p "$INSTALL_DIR"
    mkdir -p "$LOG_DIR"
    chown -R "$USER:$GROUP" "$INSTALL_DIR"
    chown -R "$USER:$GROUP" "$LOG_DIR"
    echo -e "${GREEN}✅ Directories created${NC}"
}

# Function to install dependencies
install_dependencies() {
    echo -e "\n${YELLOW}📦 Installing dependencies...${NC}"
    apt-get update
    apt-get install -y \
        wget \
        curl \
        git \
        build-essential \
        nginx \
        redis-server \
        ufw
    echo -e "${GREEN}✅ Dependencies installed${NC}"
}

# Function to install Go
install_go() {
    echo -e "\n${YELLOW}🔧 Checking Go installation...${NC}"
    if command -v go &> /dev/null; then
        GO_VERSION=$(go version | awk '{print $3}')
        echo -e "${GREEN}✅ Go already installed: $GO_VERSION${NC}"
    else
        echo "Installing Go 1.23..."
        wget https://go.dev/dl/go1.23.0.linux-amd64.tar.gz
        rm -rf /usr/local/go
        tar -C /usr/local -xzf go1.23.0.linux-amd64.tar.gz
        rm go1.23.0.linux-amd64.tar.gz
        
        # Add to PATH
        if ! grep -q "/usr/local/go/bin" /etc/profile; then
            echo 'export PATH=$PATH:/usr/local/go/bin' >> /etc/profile
        fi
        export PATH=$PATH:/usr/local/go/bin
        
        echo -e "${GREEN}✅ Go installed${NC}"
    fi
}

# Function to install Node.js for dashboard
install_nodejs() {
    echo -e "\n${YELLOW}🔧 Checking Node.js installation...${NC}"
    if command -v node &> /dev/null; then
        NODE_VERSION=$(node --version)
        echo -e "${GREEN}✅ Node.js already installed: $NODE_VERSION${NC}"
    else
        echo "Installing Node.js 20 LTS..."
        curl -fsSL https://deb.nodesource.com/setup_20.x | bash -
        apt-get install -y nodejs
        echo -e "${GREEN}✅ Node.js installed${NC}"
    fi
}

# Function to build Go binaries
build_binaries() {
    echo -e "\n${YELLOW}🔨 Building binaries...${NC}"
    
    cd "$SOURCE_DIR"
    
    if [ "$COMPONENT" = "api" ] || [ "$COMPONENT" = "all" ]; then
        echo "Building API..."
        CGO_ENABLED=0 go build -ldflags='-w -s' -o nexus-api ./cmd/api/main.go
        chmod +x nexus-api
        mv nexus-api "$INSTALL_DIR/"
        echo -e "${GREEN}✅ API binary built${NC}"
    fi
    
    if [ "$COMPONENT" = "agent" ] || [ "$COMPONENT" = "all" ]; then
        echo "Building Agent..."
        CGO_ENABLED=0 go build -ldflags='-w -s' -o nexus-agent ./cmd/agent/main.go
        chmod +x nexus-agent
        mv nexus-agent "$INSTALL_DIR/"
        echo -e "${GREEN}✅ Agent binary built${NC}"
    fi
    
    chown "$USER:$GROUP" "$INSTALL_DIR/nexus-api" "$INSTALL_DIR/nexus-agent" 2>/dev/null || true
}

# Function to setup environment
setup_environment() {
    echo -e "\n${YELLOW}⚙️  Setting up environment...${NC}"
    
    if [ ! -f "$INSTALL_DIR/.env" ]; then
        echo "Creating .env file..."
        cat > "$INSTALL_DIR/.env" << 'EOF'
# Generated by deploy script
# PLEASE UPDATE THESE VALUES!

# API Configuration
NEXUS_HTTP_ADDR=:8080
NEXUS_API_KEY=CHANGE-THIS-NOW

# AWS DynamoDB
NEXUS_DYNAMO_ENDPOINT=
NEXUS_AWS_REGION=ap-southeast-1
AWS_ACCESS_KEY_ID=your-access-key
AWS_SECRET_ACCESS_KEY=your-secret-key

# Redis
NEXUS_REDIS_ADDR=localhost:6379
NEXUS_REDIS_PASSWORD=CHANGE-THIS-NOW

# Agent (if applicable)
NEXUS_API_BASE=http://localhost:8080
NEXUS_AGENT_API_KEY=CHANGE-THIS-NOW
NEXUS_NODE_TOKEN=get-from-dashboard
NEXUS_NODE_DOMAIN=short.yourdomain.com
EOF
        
        chown "$USER:$GROUP" "$INSTALL_DIR/.env"
        chmod 600 "$INSTALL_DIR/.env"
        
        echo -e "${YELLOW}⚠️  .env file created - PLEASE UPDATE IT!${NC}"
        echo -e "${YELLOW}   Edit: sudo nano $INSTALL_DIR/.env${NC}"
    else
        echo -e "${GREEN}✅ .env file already exists${NC}"
    fi
}

# Function to install systemd service
install_systemd_service() {
    local service=$1
    echo -e "\n${YELLOW}🔧 Installing systemd service: $service${NC}"
    
    local service_file="$SOURCE_DIR/deployment/systemd/nexuslink-${service}.service"
    local dest_file="/etc/systemd/system/nexuslink-${service}.service"
    
    if [ -f "$service_file" ]; then
        cp "$service_file" "$dest_file"
        systemctl daemon-reload
        systemctl enable "nexuslink-${service}"
        echo -e "${GREEN}✅ Service nexuslink-${service} installed${NC}"
    else
        echo -e "${RED}❌ Service file not found: $service_file${NC}"
    fi
}

# Function to configure firewall
configure_firewall() {
    echo -e "\n${YELLOW}🔥 Configuring firewall...${NC}"
    
    ufw --force enable
    ufw allow 22/tcp    # SSH
    ufw allow 80/tcp    # HTTP
    ufw allow 443/tcp   # HTTPS
    
    if [ "$COMPONENT" = "api" ] || [ "$COMPONENT" = "all" ]; then
        ufw allow 8080/tcp  # API (optional, jika tidak pakai reverse proxy)
    fi
    
    if [ "$COMPONENT" = "agent" ] || [ "$COMPONENT" = "all" ]; then
        ufw allow 9090/tcp  # Agent (optional)
    fi
    
    ufw reload
    echo -e "${GREEN}✅ Firewall configured${NC}"
}

# Function to start services
start_services() {
    echo -e "\n${YELLOW}🚀 Starting services...${NC}"
    
    # Start Redis
    systemctl start redis-server
    systemctl enable redis-server
    echo -e "${GREEN}✅ Redis started${NC}"
    
    if [ "$COMPONENT" = "api" ] || [ "$COMPONENT" = "all" ]; then
        systemctl start nexuslink-api
        echo -e "${GREEN}✅ API started${NC}"
    fi
    
    if [ "$COMPONENT" = "agent" ] || [ "$COMPONENT" = "all" ]; then
        systemctl start nexuslink-agent
        echo -e "${GREEN}✅ Agent started${NC}"
    fi
}

# Function to check services status
check_status() {
    echo -e "\n${BLUE}📊 Service Status:${NC}"
    
    if [ "$COMPONENT" = "api" ] || [ "$COMPONENT" = "all" ]; then
        systemctl status nexuslink-api --no-pager || true
    fi
    
    if [ "$COMPONENT" = "agent" ] || [ "$COMPONENT" = "all" ]; then
        systemctl status nexuslink-agent --no-pager || true
    fi
}

# Main deployment flow
main() {
    echo -e "${YELLOW}Deploying component: $COMPONENT${NC}\n"
    
    create_user
    create_directories
    install_dependencies
    
    if [ "$COMPONENT" != "dashboard" ]; then
        install_go
    fi
    
    if [ "$COMPONENT" = "dashboard" ]; then
        install_nodejs
        echo -e "${YELLOW}Note: Dashboard deployment requires Next.js build${NC}"
        echo -e "${YELLOW}Please run: npm run build in dashboard directory${NC}"
        exit 0
    fi
    
    # Clone or copy source code
    if [ -d "$INSTALL_DIR/nexuslink/cmd" ]; then
        echo "Found source code in subdirectory..."
        SOURCE_DIR="$INSTALL_DIR/nexuslink"
    elif [ -d "$INSTALL_DIR/cmd" ]; then
        echo "Found source code in root..."
        SOURCE_DIR="$INSTALL_DIR"
    else
        echo -e "${YELLOW}⚠️  Source code not found in $INSTALL_DIR${NC}"
        echo "Please copy your source code to $INSTALL_DIR first"
        echo "Example: sudo cp -r /path/to/nexuslink/* $INSTALL_DIR/"
        exit 1
    fi
    
    build_binaries
    setup_environment
    
    if [ "$COMPONENT" = "api" ] || [ "$COMPONENT" = "all" ]; then
        install_systemd_service "api"
    fi
    
    if [ "$COMPONENT" = "agent" ] || [ "$COMPONENT" = "all" ]; then
        install_systemd_service "agent"
    fi
    
    configure_firewall
    start_services
    check_status
    
    # Final instructions
    echo -e "\n${GREEN}✅ Deployment Complete!${NC}"
    echo "----------------------------------------"
    echo -e "${YELLOW}Next Steps:${NC}"
    echo "1. Update .env file: sudo nano $INSTALL_DIR/.env"
    echo "2. Restart services: sudo systemctl restart nexuslink-api"
    echo "3. Check logs: sudo journalctl -u nexuslink-api -f"
    echo "4. Setup SSL: sudo bash $INSTALL_DIR/deployment/scripts/setup-ssl.sh"
    echo ""
    echo -e "${BLUE}Useful Commands:${NC}"
    echo "  Status:  sudo systemctl status nexuslink-api"
    echo "  Stop:    sudo systemctl stop nexuslink-api"
    echo "  Start:   sudo systemctl start nexuslink-api"
    echo "  Restart: sudo systemctl restart nexuslink-api"
    echo "  Logs:    sudo journalctl -u nexuslink-api -f"
}

# Run main function
main
